### ISSUE TITLE
NotImplementedError: method `hash' called on unexpected T_NODE object

### ISSUE THREAD

**Issue by msievers** [ohler55/ox#106]
While executing Ox.parse I randomly get

```
NotImplementedError: method `hash' called on unexpected T_NODE object
```

Even if the input is the same, this error only occurs randomly. I am using Ruby 2.2, so maybe it's related to the symbol garbage collection like #103.

I'm using the current master.

**Comment by msievers** [comment]
I've created a Gem which isolates the scenario where my code triggers this.

https://github.com/msievers/potential_ox_bug

Running

```
rake run
```

Setting ```GC.stress = true``` it coredumps with ruby 2.2 but not with 2.1. I'm not sure if this is related, because I don't get a coredump with my original code, but maybe it is.

Sadly I was not able to trigger

```
NotImplementedError: method `hash' called on unexpected T_NODE object
```

by now with this Gem, although it's the same xml data and the same instructions as used in my original code.

**Comment by ohler55** [comment]
I'll dig into it this week. There are certainly differences with GC on 2.2.

**Comment by hakanensari** [comment]
I've also been running into this intermittently in a threaded environment (Sidekiq) with 2.2. Sadly, I can't reproduce the seemingly random errors.

**Comment by ohler55** [comment]
It sounds like an object node reuse after GC. With the test case provided by msievers I should be able to debug the problem.

**Comment by 7Dump** [comment]
I also get a this bug, EventMachine with ox and 2.2 ruby

**Comment by gbiczo** [comment]
I too encounter intermittently this error with oxcelix 4.0 and ruby 2.2

**Comment by ohler55** [comment]
I have a version on github master that is a release candidate. I believe the Symbol GC problem that can with the new Ruby 2.2 GC is fixed. The test by msievers is passing for me after 1000 iterations. Please give it a try and I'll release after I get some feedback.

**Comment by gbiczo** [comment]
Works like a charm for me testing oxcelix 0.4, thank you!

**Comment by ohler55** [comment]
If anyone cares about the details, the only way I could reproduce the problem was with the potential_ox_bug installed as a gem. The problem was indeed related to the new symbol GC in Ruby 2.2. Ox creates symbols when in symbolize_keys mode. Since most XML documents are UTF-8 the symbols can not all be created with the rb_intern() call as that does not suppose specifying an encoding. The only way I have found is to create a string, force encoding on it, and then convert to a symbol. Unfortunately that can only be done with Ruby calls which allow the Symbol to be garbage collected. The work around was to place the symbols in a protected Array so they would not be collected.

**Comment by msievers** [comment]
For me there are no errors with the current master so I close this as solved.

Thank you very much!
