### ISSUE TITLE
Remove handler.error call when doctype is not in caps

### ISSUE THREAD

**Issue by otaviocardoso** [ohler55/ox#136]
`Ox.sax_parse` calls `handler.error` when the doctype instruction is not all in caps.
But according with W3C definition, the doctype matching should be case-insensitive.

https://www.w3.org/TR/html-markup/syntax.html#doctype-syntax
http://www.w3.org/TR/html5/syntax.html#the-doctype

**Comment by ohler55** [comment]
To be pedantic, the w3 specs for html indicate doctype is case insensitive. For XML it is not. In tolerant mode Ox allows case insensitive. That is what is used for parsing html as the html format is not a subset of XML. It is a much looser spec mostly due to legacy usage.

I do see that Ox does a case insensitive compare in tolerant mode but not when the smart flag is set. That should probably be changed so that case insensitive compares are done then also. I'd prefer to leave strict mode strict though.

**Comment by otaviocardoso** [comment]
Oh, I was not aware about the tolerant mode, just found strange the error about the doctype case.

And thanks, this answer was fast!!

**Comment by ohler55** [comment]
Your English was perfect. No worries there. I'll leave this issue open until I make the change I mentioned though.

**Comment by ohler55** [comment]
After looking at the code I see that the :smart option is only for the SAX parser. To have better success with html use the :effort => :tolerant option. Still don't expect 100% as a lot of html is pretty non-conformant.

**Comment by otaviocardoso** [comment]
Ok, I'm already using `:effort => :tolerant`, currently without problems.

**Comment by ohler55** [comment]
Great. Shall we close this issue then?

**Comment by otaviocardoso** [comment]
Sure!
