### ISSUE TITLE
Element whitelist

### ISSUE THREAD

**Issue by Zapotek** [ohler55/ox#142]
Would it be possible to add an element whitelisting option to Ox?
Something like a list of elements by tag name that are allowed to be converted into `Ox::Element`s, with the children of the skipped nodes forwarded to the nearest parent?

This is a bit weird I'll grant you, but for people in my position it would make a world of difference.

I'd do this myself via the SAX parser, but once Ruby got involved performance dropped like a stone.

**Comment by ohler55** [comment]
That is indeed becoming too specialized for Ox. That is really application code. If performance is critical, you might be more interested in the OjC parser that is strictly in C. You could write the component in C instead of Ruby. If you want to discuss some ways to make the languages fit together nicely lets discuss off-line by email.

**Comment by Zapotek** [comment]
Yeah that's fair enough.
